site:
    title: Payara Documentation Preview
    start_page: docs::README.adoc
content:
    sources:
    - url: ./
      start_path: docs
      branches: HEAD
asciidoc:
    attributes:
        attribute-missing: 'skip'
ui:
    bundle:
        url: https://github.com/payara/antora-ui-default/raw/master/build/ui-bundle.zip
        snapshot: true
runtime:
    fetch: true
output:
    dir: ./build/html
